/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as NewsNewsRouteImport } from './routes/_news/news'
import { Route as NewsSlugSlugRouteImport } from './routes/_news/$slug/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsRoute = NewsNewsRouteImport.update({
  id: '/_news/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugSlugRoute = NewsSlugSlugRouteImport.update({
  id: '/_news/$slug/$slug',
  path: '/$slug/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/news': typeof NewsNewsRoute
  '/$slug/$slug': typeof NewsSlugSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/news': typeof NewsNewsRoute
  '/$slug/$slug': typeof NewsSlugSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_news/news': typeof NewsNewsRoute
  '/_news/$slug/$slug': typeof NewsSlugSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/news' | '/$slug/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/news' | '/$slug/$slug'
  id: '__root__' | '/' | '/$' | '/_news/news' | '/_news/$slug/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  NewsNewsRoute: typeof NewsNewsRoute
  NewsSlugSlugRoute: typeof NewsSlugSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_news/news': {
      id: '/_news/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_news/$slug/$slug': {
      id: '/_news/$slug/$slug'
      path: '/$slug/$slug'
      fullPath: '/$slug/$slug'
      preLoaderRoute: typeof NewsSlugSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  NewsNewsRoute: NewsNewsRoute,
  NewsSlugSlugRoute: NewsSlugSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
